---
version: "2"
networks:
  macvlan0:
    name: macvlan0
    driver: macvlan
    driver_opts:
      parent: enp4s0f3u2
    ipam:
      config:
      - subnet: "10.0.99.0/24"
        ip_range: "10.0.99.0/24"
        gateway: :10.0.99.1"
services: 
  ocpdiscon-registry: 
    image: docker.io/library/registry:2
    ports:
        - "5051:5000"
    environment:
        - REGISTRY_AUTH=htpasswd
        - REGISTRY_AUTH_HTPASSWD_REALM=Registry
        - REGISTRY_HTTP_SECRET=ALongRandomSecretForRegistry
        - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
        - REGISTRY_HTTP_TLS_CERTIFICATE=certs/domain.crt
        - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
        - REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true
        - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
        - /apps/registry/data:/var/lib/registry
        - /apps/registry/auth:/auth
        - /apps/registry/certs:/certs
    labels:
        my.label: registry
    networks:
        macvlan0:
          ipv4_address: 10.0.99.5
  httpd-server:
    image: 
    ports: 
        - "3000:8080"
    volumes:
        - /apps/rhcos_image_cache:/var/www/html
    labels:
        my.label: httpd-abi
    networks:
        macvlan0:
          ipv4_address: 10.0.99.4

