---
version: "2"
services:
  ocpdiscon-registry:
    restart: always
    image: quay.io/midu/registry:latest
    ports:
        - "5000:5000"
    environment:
        - REGISTRY_AUTH=htpasswd
        - REGISTRY_AUTH_HTPASSWD_REALM=Registry
        - REGISTRY_HTTP_SECRET=ALongRandomSecretForRegistry
        - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
        - REGISTRY_HTTP_TLS_CERTIFICATE=certs/domain.crt
        - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
        - REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true
        - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
        - /apps/registry/data:/var/lib/registry:z
        - /apps/registry/auth:/auth:z
        - /apps/registry/certs:/certs:z
    labels:
        my.label: ocpdiscon_registry
  rhcos_image_cache:
    restart: always
    image: quay.io/midu/httpd:latest
    ports: 
        - "3000:8080"
    volumes:
        - /apps/rhcos_image_cache:/var/www/html:z
    labels:
        my.label: rhcos_image_cache
  rhocp-dns:
    restart: always
    image: quay.io/midu/dns:latest
    volumes:
        - /apps/bind/primary:/data:z
    ports:
        - "53:53/tcp"
        - "53:53/udp"
    labels:
        my.label: rhocp_bind9
  rhocp-dhcp:
    image: quay.io/midu/dhcpd:latest
    networks:
      internal_network:
          ipv4_address: 10.0.99.2
    volumes:
        - /apps/dhcp:/etc/dhcp:z
    labels:
        my.label: rhocp_dhcp