FROM docker.io/library/centos:7
MAINTAINER midu@redhat.com
# downloading the oc-cli and oc-mirror-cli 
WORKDIR / 
RUN curl -O -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.12.2/openshift-client-linux.tar.gz \
 tar  zxvf openshift-client-linux.tar.gz \
 cp -r kubectl oc /usr/local/bin/ \
 /usr/local/bin/oc version 

RUN curl -O -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.12.2/oc-mirror.tar.gz \
 tar  zxvf oc-mirror \
 chown a+x ./oc-mirror \
 cp oc-mirror /usr/local/bin \
 /usr/local/bin/oc-mirror version

CMD ["/bin/bash"]