FROM docker.io/library/centos:7
MAINTAINER midu@redhat.com
# downloading the oc-cli and oc-mirror-cli 
WORKDIR / 
RUN curl -O -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.12.2/openshift-client-linux.tar.gz 
RUN tar zxvf openshift-client-linux.tar.gz 
RUN cp -r kubectl oc /usr/local/bin/ 
RUN  /usr/local/bin/oc version 
WORKDIR / 
RUN curl -O -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.12.2/oc-mirror.tar.gz
RUN tar zxvf oc-mirror.tar.gz
RUN chmod 777 /oc-mirror
RUN cp oc-mirror /usr/local/bin 
RUN /usr/local/bin/oc-mirror version

CMD ["/bin/bash"]