FROM docker.io/internetsystemsconsortium/bind9:9.18

RUN apt update \
  && apt install -y \
  bind9-doc \
  dnsutils \
  geoip-bin \
  mariadb-server \
  net-tools

# Parsing the configration as a argument
ARG options
ARG local
ARG zones

ENV env_options=${options}
ENV env_local=${local}
ENV env_zones=${zones}
# Copy configuration files
COPY ${env_options} /etc/bind/
COPY ${env_local} /etc/bind/
COPY ${env_zones} /etc/bind/zones/

# Expose Ports
EXPOSE 53/tcp
EXPOSE 53/udp
EXPOSE 953/tcp

# Start the Name Service
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]